### ISSUE TITLE
Crashed when call close() in CefWnd

### ISSUE THREAD

**Issue by xp19870106** [winsoft666/QCefWidget#10]
If I call close() in frameless CefWnd, the app will be easily crashed(repeat open-close like 10 times, then it crahed)
![1](https://user-images.githubusercontent.com/5085902/117666011-ffa3b000-b1d5-11eb-8289-e9e5c7f29674.png)

**Comment by xp19870106** [comment]
It seems that sometimes the QCefWidgetImpl was destroyed before QCefBrowserHandler

**Comment by xp19870106** [comment]
Why this method never called
void QCefManager::removeCefWidget(QWidget* pCefWidget)
then in bool QCefManager::eventFilter(QObject* obj, QEvent* event) ,
 if (!pImp->browserSetting().autoDestroyCefWhenCloseEvent) may return true

**Comment by xp19870106** [comment]
@winsoft666

**Comment by xp19870106** [comment]
maybe you should add 
      it->cefWidgetTopWidget = nullptr;
in 
void QCefManager::setBrowserClosed(QWidget* pCefWidget)

**Comment by winsoft666** [comment]
Exit logic has been optimized.
Please try again.
