### ISSUE TITLE
Can not exist with QWebEngineView in same project

### ISSUE THREAD

**Issue by xp19870106** [winsoft666/QCefWidget#11]
m_web = new PluginWebView();
    ui->verticalLayout->addWidget(m_web);
    m_web->setUrl("www.baidu.com");
    QWebEngineView* test = new QWebEngineView();
    ui->verticalLayout->addWidget(test);

then it will crash like this
![1](https://user-images.githubusercontent.com/5085902/117822469-2b3e9d00-b29f-11eb-9652-376341ac6b03.png)

**Comment by winsoft666** [comment]
what's `PluginWebView`?
