### ISSUE TITLE
可以支持macOS, 和Linux吗

### ISSUE THREAD

**Issue by wangqiangcc** [winsoft666/QCefWidget#15]
你好
      可以支持macOS, 和Linux吗?
如果能支持，麻烦编译一份支持 macOS 和Linux libcef （支持 mp4, h264 功能）

     感谢~！

**Comment by winsoft666** [comment]
不支持

**Comment by lanmanck** [comment]
希望大佬支持！国产是趋势！

**Comment by winsoft666** [comment]
嗯嗯，这个已经在计划中了

**Comment by winsoft666** [comment]
QCefWidget已升级到QWebView
