### ISSUE TITLE
Help request for loading an internal "qrc" resource

### ISSUE THREAD

**Issue by ShelleyLake** [winsoft666/QCefWidget#18]
I wanted to ask if you have any idea how to load an internal resource, e.g. by entering the qrc path in the address bar of the example application. Both of the following syntaxes are not working:
```
"qrc:/QCefWidgetTest/images/visible.svg"
":/QCefWidgetTest/images/visible.svg"
```

Thanks in advance

**Comment by winsoft666** [comment]
Hi guys, you need modify `loadBinaryResource` function in QCefResourceUtil.cpp.
