### ISSUE TITLE
cef_binary_80.1.15+g7b802c9+chromium-80.0.3987.163_windows32编译失败

### ISSUE THREAD

**Issue by oopses** [winsoft666/QCefWidget#2]
下载cef_binary_80.1.15+g7b802c9+chromium-80.0.3987.163_windows32版本进行编译后大量报错，CEF的API升级造成的

**Comment by winsoft666** [comment]
Above 3626, you maybe need redefine some function.

**Comment by winsoft666** [comment]
See dep/README.md

**Comment by oopses** [comment]
已经采用80版本的编译成功，目前运行后网页无法加载 问题还在查找
