### ISSUE TITLE
OSR模式下，浮起的图片用鼠标抓取后再松开，图片仍不会释放

### ISSUE THREAD

**Issue by qihaoxi** [winsoft666/QCefWidget#24]
OSR模式下， 网页的图片如果点击后可以浮起查看的，用鼠标抓取后再松开，发现仍然跟随鼠标移动。
qt 5.13.2 cef_binary_87.1.14+ga29e9a3+chromium-87.0.4280.88_windows32

**Comment by qihaoxi** [comment]
5.15.2 + cef_binary_89.0.18+gb36241d+chromium-89.0.4389.114_windows32  在osr模式下测试也有问题

**Comment by winsoft666** [comment]
请提供一个测试网址

**Comment by qihaoxi** [comment]
https://www.veer.com/illustration/385095001  点击中心放大后 可以鼠标抓取

**Comment by winsoft666** [comment]
OK, fixed
