### ISSUE TITLE
64位  cmake之后编译错误

### ISSUE THREAD

**Issue by bairutai** [winsoft666/QCefWidget#25]
QCefBrowserHandler.cpp(187): error C2664: 'QString QString::arg(const QString &,int,QChar) const': cannot convert argument 1 from 'std::wstring' to 'qlonglong'   
QCefWidgetImpl.cpp(514): error C2665: 'QMetaObject::invokeMethod': none of the 4 overloads could convert all the argument types
qt5.9.9

**Comment by winsoft666** [comment]
我测试了`79.0.3945.117_windows64`版本，可以正常编译。

请确保config.cmake文件的中的CEF版本配置正确，如：
```
set(CEF_SDK_DIR "${CMAKE_CURRENT_SOURCE_DIR}/dep/cef_binary_79.1.29+ga5bf6d5+chromium-79.0.3945.117_windows64")
```

```
SET(CEF_VERSION_MAJOR 79)
SET(CEF_VERSION_MINOR 1)
SET(CEF_VERSION_PATCH 29)
```

**Comment by bairutai** [comment]
应该是qt版本的问题，低版本的qt有些api不太一样

**Comment by winsoft666** [comment]
可能，我用的是Qt5.15.2
