### ISSUE TITLE
Qt 5.12.10 QWidget不存在screen函数

### ISSUE THREAD

**Issue by m4wayne** [winsoft666/QCefWidget#26]
你好winsoft666，我目前使用的Qt版本是Qt5.12.10。更新QCefWidget后发QCefWidgetImpl使用了screen函数，但是Qt5.12.10不存在screen函数。
`connect(pWidget_->window()->screen(), &QScreen::logicalDotsPerInchChanged, this, &QCefWidgetImpl::onScreenLogicalDotsPerInchChanged);`

这个功能是不是应该做Qt版本兼容，还是QWidget已经放弃兼容Qt 5.12.10这个版本了？谢谢

**Comment by winsoft666** [comment]
Qt目前最新的官方稳定版本是5.15.x



-------- 原始信息 --------
发件人： m4wayne ***@***.***>
日期: 2021/9/18 17:25 (GMT+08:00)
收件人： winsoft666/QCefWidget ***@***.***>
抄送： Subscribed ***@***.***>
主题： [winsoft666/QCefWidget] Qt 5.12.10 QWidget不存在screen函数 (#26)


你好winsoft666，我目前使用的Qt版本是Qt5.12.10。更新后QCefWidget发QCefWidgetImpl使用了screen函数，但是Qt5.12.10不存在screen函数。
connect(pWidget_->window()->screen(), &QScreen::logicalDotsPerInchChanged, this, &QCefWidgetImpl::onScreenLogicalDotsPerInchChanged);

这个功能是不是应该做Qt版本兼容，还是QWidget已经放弃兼容Qt 5.12.10这个版本了？谢谢

―

**Comment by m4wayne** [comment]
明白。祝中秋快乐
