### ISSUE TITLE
Hyperlinks not work under the QCefWidgetTest program

### ISSUE THREAD

**Issue by ghost** [winsoft666/QCefWidget#28]
Hi there, I was compiling the project and the test program QCefWidgetTest was generated. If I set the url to "https://www.bing.com", and open it in a separate window, search with some keyword and I was not able to open any  Hyperlink. What could be the cause?

**Comment by winsoft666** [comment]
bing.com默认使用popup打开搜索结果，需要响应`void popupWindow(const QString& url)`信号，创建新的QCefWidget去打开该url

**Comment by winsoft666** [comment]
Has added sample to QCefWidgetTest project
