### ISSUE TITLE
只需要设置CSS属性，就可以实现像Electron一样拖拽无边框窗体.

### ISSUE THREAD

**Issue by weijianfa** [winsoft666/QCefWidget#3]
hello，这个有demo吗？
另外在qt项目引入QCefWidget之后导致父widget无边框无法拖放，WM_NCHITTEST消息被屏蔽，这是什么原因呢？
多谢解答！

**Comment by winsoft666** [comment]
不好意思，回复晚了，在QCefWidgetTest项目中已经有Demo了：
点击“Simulate Electron”按钮快速设置，点击”New Browser with Options“按钮将会使用配置的属性创建相应窗体。
