### ISSUE TITLE
Debug状态下，双击界面标题栏，直接崩溃

### ISSUE THREAD

**Issue by reghtml** [winsoft666/QCefWidget#31]
创建浏览器窗口的代码：
`myCef::myCef(QWidget *parent)
    : QMainWindow(parent)
{
    ui.setupUi(this);

    //关联事件
    connect(ui.btn_go, &QPushButton::clicked, this, &myCef::btn_go_clicked);

    //初始化CEF
    pCefWnd = new CefWnd(false, false);
    connect(pCefWnd, &QWidget::destroyed, this, &myCef::onCefWndDestroyed);//销毁浏览器
    pCefWnd->setUsingGLWidget(true);//启用opengl
    pCefWnd->setOsrEnabled(true);//离屏渲染
    pCefWnd->setContextMenuEnabled(true);//右键菜单
    pCefWnd->setUsingHideInsteadClose(false);//隐藏代替u绀碧
    pCefWnd->setAutoAddDevToolsContextMenu(true);//检查元素右键菜单
    pCefWnd->setAllowExecuteUnknownProtocolViaOS(true);//设置允许执行未知协议
    pCefWnd->setMaximumFps(30);//设置最大帧率
    //pCefWnd->setWindowBkColor(winBkColor);//设置窗口背景色
    //pCefWnd->setBrowserBkColor(browserBkColor); //浏览器背景色
    
    pCefWnd->setInitSize(QSize(800, 600)); //初始化大小
    pCefWnd->setInitUrl("http://www.baidu.com");     
    ui.layout_body->addWidget(pCefWnd);
    pCefWnd->setupUi();
    pCefWnd->show(); //显示浏览器
}`

![image](https://user-images.githubusercontent.com/15364651/145660349-42c23cea-59c6-499b-8d03-3247d74ce196.png)

直接报错了：
![image](https://user-images.githubusercontent.com/15364651/145660365-ec33f781-cfda-489c-8ef0-0b96275be4de.png)

同样的代码不变，换成release模式，就不会有这种问题，请问是什么原因呢

**Comment by androrz** [comment]
用源码自带的demo在debug模式下双击标题栏会不会崩溃呢

**Comment by androrz** [comment]
> 创建浏览器窗口的代码： `myCef::myCef(QWidget *parent) : QMainWindow(parent) { ui.setupUi(this);
> 
> ```
> //关联事件
> connect(ui.btn_go, &QPushButton::clicked, this, &myCef::btn_go_clicked);
> 
> //初始化CEF
> pCefWnd = new CefWnd(false, false);
> connect(pCefWnd, &QWidget::destroyed, this, &myCef::onCefWndDestroyed);//销毁浏览器
> pCefWnd->setUsingGLWidget(true);//启用opengl
> pCefWnd->setOsrEnabled(true);//离屏渲染
> pCefWnd->setContextMenuEnabled(true);//右键菜单
> pCefWnd->setUsingHideInsteadClose(false);//隐藏代替u绀碧
> pCefWnd->setAutoAddDevToolsContextMenu(true);//检查元素右键菜单
> pCefWnd->setAllowExecuteUnknownProtocolViaOS(true);//设置允许执行未知协议
> pCefWnd->setMaximumFps(30);//设置最大帧率
> //pCefWnd->setWindowBkColor(winBkColor);//设置窗口背景色
> //pCefWnd->setBrowserBkColor(browserBkColor); //浏览器背景色
> 
> pCefWnd->setInitSize(QSize(800, 600)); //初始化大小
> pCefWnd->setInitUrl("http://www.baidu.com");     
> ui.layout_body->addWidget(pCefWnd);
> pCefWnd->setupUi();
> pCefWnd->show(); //显示浏览器
> ```
> 
> }`
> 
> ![image](https://user-images.githubusercontent.com/15364651/145660349-42c23cea-59c6-499b-8d03-3247d74ce196.png)
> 
> 直接报错了： ![image](https://user-images.githubusercontent.com/15364651/145660365-ec33f781-cfda-489c-8ef0-0b96275be4de.png)
> 
> 同样的代码不变，换成release模式，就不会有这种问题，请问是什么原因呢

找到问题了吗

**Comment by realwqsz** [comment]
pCefWnd->setOsrEnabled(true);//离屏渲染
你把离屏渲染关了试试.

**Comment by wangdemon** [comment]
直接调用delete CefWnd类对象,会导致程序崩溃，或者让整个程序隐藏

**Comment by winsoft666** [comment]
QCefWidget已升级到QWebView
