### ISSUE TITLE
建议你删除这个repo中使用了QCefView的所有代码

### ISSUE THREAD

**Issue by tishion** [winsoft666/QCefWidget#33]
你可以从QCefView fork修改，但是你这种直接修改文档当作新项目发布的行为不合理。

如果觉得QCefView对你很有帮助或者启发，请遵守开源协议进行贡献：
https://github.com/CefView/QCefView

**Comment by winsoft666** [comment]
Fixed!

**Comment by tishion** [comment]
👍
