### ISSUE TITLE
本项目是否可以集成本地服务的three.js的项目

### ISSUE THREAD

**Issue by MW8023** [winsoft666/QCefWidget#34]
试了一下大佬的项目输入本地web服务的three.js可以正常的打开  不知道可不可以进行交互

**Comment by winsoft666** [comment]
可以描述一下具体需求吗？按理应该可以

**Comment by winsoft666** [comment]
需要怎么样的交互

**Comment by MW8023** [comment]
谢谢你们的这个框架 现在的问题已经解决了 在网上找到了一大堆也没有适配 非常感谢解决了我们的燃眉之急 也希望你们的框架会被很多人使用到



在 2022-03-25 18:56:27，"winsoft666" ***@***.***> 写道：

需要怎么样的交互

**Comment by winsoft666** [comment]
不客气

**Comment by winsoft666** [comment]
QCefWidget已升级到QWebView
