### ISSUE TITLE
5.12.10编译有错误

### ISSUE THREAD

**Issue by IULOVE** [winsoft666/QCefWidget#36]
TestWnd.cpp(225,46): error C2039: "SkipEmptyParts": 不是 "Qt" 的成员

还有这个 connect(pWidget_->window()->screen(), &QScreen::logicalDotsPerInchChanged, this, &QCefWidgetImpl::onScreenLogicalDotsPerInchChanged);

**Comment by IULOVE** [comment]
改完编译出来打开的网页都是这样的
![Quicker_20220507_124629](https://user-images.githubusercontent.com/14193276/167238761-388b317c-2843-48a0-a847-65c5c5ac4cf6.png)

**Comment by winsoft666** [comment]
Sorry, I don't have this Qt version. 
You can fix this problem, and pull a request.

**Comment by winsoft666** [comment]
QCefWidget已升级到QWebView
