### ISSUE TITLE
JavaScript Callbacks?

### ISSUE THREAD

**Issue by ShelleyLake** [winsoft666/QCefWidget#4]
Dear @winsoft666 , I kindly ask you if it would be possible to implement JS Callbacks as described here:
https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration

**Comment by winsoft666** [comment]
yes, QCefWidget has implemented JS callback like this wiki.







-------- 原始信息 --------
发件人： Shelley Lake ***@***.***>
日期: 2021/3/18 07:03 (GMT+08:00)
收件人： winsoft666/QCefWidget ***@***.***>
抄送： winsoft666 ***@***.***>, Mention ***@***.***>
主题： [winsoft666/QCefWidget] JavaScript Callbacks? (#4)


Dear @winsoft666<https://github.com/winsoft666> , I kindly ask you if it would be possible to implement JS Callbacks as described here:
https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration

―

**Comment by ShelleyLake** [comment]
If I see correctly, you've implemented "ExecuteJavaScript" which can call a Javascript function from C++...
...but is there a way to get back a value from Javascript to C++?
As stated by the documentation: `The ExecuteJavaScript() function can be used to interact with functions and variables in the frame's JS context. In order to return values from JS to the client application consider using Window Binding or Extensions.`
Do you have a way, and maybe an example how to trigger a JS function and get its value back to c++?
Many thank.

**Comment by winsoft666** [comment]
"QCefWidget\test\QCefWidgetTest" is a full sample, include C++ / JavaScript call each other.

In CefWnd.cpp search follow key string:
onCefQueryRequest
triggerEvent

**Comment by winsoft666** [comment]
triggerEvent is an async function, if you want to get response from JavaScript, you can wrapper custom protocol by using triggerEvent  and invokeMethodNotify.

- triggerEvent : C++ call JS.
- invokeMethodNotify: JS call C++.
- cefQueryRequest: JS call C++, but it can send a response to C++.

**Comment by ShelleyLake** [comment]
Thank you very much.
I'll have a try!
