### ISSUE TITLE
如何设置命令行参数

### ISSUE THREAD

**Issue by wangdemon** [winsoft666/QCefWidget#41]
在cef sdk中，有个cefclient的程序，如果要cefclient支持webrtc，就添加enable-media-stream命令行参数即可。

在QCefWidget中，如何添加类似的参数？

**Comment by wangdemon** [comment]
只要前端调用getDisplayMedia函数，就会报错NotAllowedError，如下图所示

![1](https://user-images.githubusercontent.com/20681339/212290529-5a008306-927c-49c1-94bf-55e7fe5e8a37.PNG)


![2](https://user-images.githubusercontent.com/20681339/212290564-38bd21a3-701d-4310-bd6a-a84894281af1.png)

**Comment by winsoft666** [comment]
QCefWidget已升级到QWebView
