### ISSUE TITLE
OSR模式下，不断的改变窗口大小时，容易崩溃

### ISSUE THREAD

**Issue by LiJem** [winsoft666/QCefWidget#5]
在启用OSR模式下，不断的改变窗口大小时，容易崩溃；
非OSR不会出现此问题，我的CEF版本为：cef_binary_76.1.13+gf19c584+chromium-76.0.3809.132_windows32

**Comment by winsoft666** [comment]
你好，问题已经收到，正在解决中

**Comment by winsoft666** [comment]
我使用`cef_binary_76.1.13+gf19c584+chromium-76.0.3809.132_windows32`版本测试，没有重现该问题。

麻烦使用最新版的QCefWidget在测试一下，config.cmake如下：
```bash
set(CEF_SDK_DIR "${CMAKE_CURRENT_SOURCE_DIR}/dep/cef_binary_76.1.13+gf19c584+chromium-76.0.3809.132_windows32")

# CEF version
SET(CEF_VERSION_MAJOR 76)
SET(CEF_VERSION_MINOR 1)
SET(CEF_VERSION_PATCH 13)
```

**Comment by LiJem** [comment]
可能是我编译加入支持音视频的时候哪里有问题导致的
